[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
solc_version = "0.8.26"
evm_version = "cancun"
ffi = true
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 50 }
via_ir = true

[profile.default.fmt]
line_length = 120

[profile.ci]
fuzz = { runs = 50000 }
invariant = { runs = 5000, depth = 100 }

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
base = "${BASE_RPC_URL}"
unichain = "${UNICHAIN_RPC_URL}"
unichain_sepolia = "${UNICHAIN_SEPOLIA_RPC_URL}"

[etherscan]
unichain_sepolia = { key = "${BLOCKSCOUT_API_KEY_UNICHAIN}", url = "https://unichain-sepolia.blockscout.com/api/", chain = 1301 }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
